package com.mwshubham.notes.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.mwshubham.notes.data.local.dao.NoteDao
import com.mwshubham.notes.data.local.entity.NoteEntity

/**
 * Room database for the Notes vault.
 * [ConstructedBy] links to the expect/actual constructor so Room can instantiate
 * the database on both Android and iOS via KMP.
 */
@Database(
    entities = [NoteEntity::class],
    version = 1,
    exportSchema = true
)
@ConstructedBy(NotesDatabaseConstructor::class)
abstract class NotesDatabase : RoomDatabase() {
    abstract fun noteDao(): NoteDao
}

/**
 * Expect/actual constructor hook required by Room KMP.
 * The actual implementations are generated by KSP in each platform source set.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object NotesDatabaseConstructor : RoomDatabaseConstructor<NotesDatabase> {
    override fun initialize(): NotesDatabase
}
